### PR TITLE
Upgrade Solr to 6

### PR DESCRIPTION
**Pull request by ja-fra**
Upgraded Solr-Version from `5.5.0`/`5.5.2` to `6.2.1`

### CODE REVIEW

**Comment by BorisNaguet** [comment]
Hello, 

Sorry for the delay and thanks for this 1st pull request :)

I just have 2 questions:
* did you try to override the version in your pom like this:
```xml
				<plugin>
					<groupId>io.github.borisnaguet</groupId>
					<artifactId>solr-maven-plugin</artifactId>
					<version>0.3.0</version>
					<dependencies>
						<dependency>
							<groupId>org.apache.solr</groupId>
							<artifactId>solr-core</artifactId>
							<version>${solr.version}</version>
						</dependency>
						<dependency>
							<groupId>org.apache.solr</groupId>
							<artifactId>solr-test-framework</artifactId>
							<version>${solr.version}</version>
						</dependency>
					</dependencies>
...
```

* Why not version 6.4.1 since it's the last one ?

**Comment by ja-fra** [comment]
Didn't try overriding the `solr.version` via the dependencies... I'll try that, thanks!

Why 6.2.1 and not 6.4.1? Simply because `maven install` worked with 6.2.1 and not with 6.3 and 6.4...

**Comment by BorisNaguet** [comment]
OK keep me informed thanks.

I'll have a look at 6.3 & 6.4...

**Comment by BorisNaguet** [comment]
I built a SNAPSHOT with 6.4.1 if you want to give it a try

**Pull request merged**
